### ISSUE TITLE
Is it bug or feature?

### ISSUE THREAD

**Issue by 0fuz** [julian-shalaby/Onuro-feedback#4]
Hello, question about dropdown list of allowed files for chat context. When using claude-3 and opened .gitlab-ci.yml but not selected on dropdown menu, those chat tells how to edit .yml to do what needed. But im not allowed such file for it. 

Only one idea why this happens: any currently active file tab automatically inserted into chat context.

Tried to start new chat and ask about .yml and it writes "what now" and "what to edit"

**Comment by julian-shalaby** [comment]
This is a feature. Finding the right balance between automatically including context and leaving context as a manual selection process has been a bit non trivial.

If I leave all unselected by default, this strays away from the standard of code assistants, its a bit annoying having to constantly select the file you're on when you ask questions, and it could be confusing to new users who pick this up and just want to start seeing results right away. If I select all by default, its also quite annoying having to deselect files all the time, and inexperienced users seem to basically just flood the context all the time by not deselecting files.

I figured since this is a code assistant, you will almost always be referencing some kind of code file, and that will likely be the file you have currently focused at the very least. I am open to suggestions here on making this experience better if you have any

**Comment by 0fuz** [comment]
Its good feature in general. But were a bit not obvious.

Seems configuration files, like semi-prod .env might be opened and shared with cloud models. I understand that having production .env on dev project not correct but anyway its will present, depending on team size and development flow.

What about one-time notice about "currently opened file is auto added to chat context, so dont chat when opened files which might have confidential data like .env and etc"?

And what about mark current file on dropdown menu of files with icon like "auto added to chat context". Currently its just gray font, maybe "(i) with a notice"

**Comment by julian-shalaby** [comment]
Agreed .env and known sensitive files have no reason to be read in as defaults. Will add this to a list of files to not just read in by default. 

A 1 time notice to the user is also a good idea. I find getting all the "here's how it works" aspects of chatwindow to the user is a bit challenging, but I do want to find a way to easily get these kind of points to the user without having them open my user guide. If find there is too much to just throw at the user in 1 intro paragraph, but there's a lot the user really should know before/when using the plugin. I am adding a Q&A slash command to my next version which runs RAG on my documentation. May also add something similar to a "take a tour" like feature, if I can think of a fairly presentable way to.

Agreed the grey overlay is not intuitive. Its another 1 of those features where I just couldn't think of a great solution so far. An (i) icon I will consider and probably mess with in dev bit. Good idea, but I want to make sure it won't get annoying seeing it all the time after using the plugin for a long time.

Great points and I appreciate the feedback btw. Helps clean up the plugin a lot
